/**
 * Siltflow SQLite database row types.
 *
 * These match the Drizzle schema in electron/database/schema.ts of the
 * Siltflow desktop app. Only fields needed for import are included.
 */

export interface DocumentRow {
  id: string;
  title: string;
  original_name: string | null;
  total_pages: number | null;
  metadata: string | null; // serialized JSON
  folder_id: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface AnnotationRow {
  id: string;
  document_id: string;
  type: string; // "highlight" | "underline" | "text" | ...
  text: string | null;
  page_number: number | null;
  embed_data: string; // serialized JSON with positional/rect data
  kind: string; // "annotation" | "manual" | ...
  created_at: string;
  updated_at: string;
}

export interface AIResultRow {
  annotation_id: string;
  document_id: string;
  data: string; // serialized JSON — AI translation/explanation/etc.
  version: number; // AI data schema version
  created_at: string;
  updated_at: string;
}

export interface SummaryRow {
  document_id: string;
  text: string;
  is_ai_generated: number; // 0 or 1
  source_lang: string | null;
  created_at: string;
  updated_at: string;
}

export interface FolderRow {
  id: string;
  name: string;
  parent_id: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

/**
 * Parsed AI result — union of V1 (AIAnnotationDataV1) and V2 (AIAnnotationDataV2)
 * schemas from the upstream Siltflow desktop app.
 *
 * V1: flat structure with `translation`, `definitions`, `examples`, etc.
 * V2: `input` + `output` where `output` type depends on `input.type`
 *     (word / phrase / sentence).
 */
export interface ParsedAIResult {
  // ── V1 fields ──
  translation?: string;
  source_lang?: string;
  target_lang?: string;
  cleaned_input?: string;
  lemma?: string;
  pos?: string;
  definitions?: Array<{
    pos?: string;
    definition: string;
    gloss?: string;
  }>;
  examples?: Array<{
    sentence: string;
    translation: string;
  }>;
  collocations?: Array<{
    phrase: string;
    translation: string;
  }>;
  alternatives?: Array<{
    expression: string;
    register?: string;
  }>;
  pronunciation?: { ipa?: string };
  metadata?: {
    difficulty?: string;
    register?: string;
    tags?: string[];
  };

  // ── V2 fields ──
  input?: {
    text: string;
    normalized: string;
    source_lang: string;
    type: "word" | "phrase" | "sentence";
    lemma?: string | null;
  };
  context?: string | null;
  /** V2 output — shape depends on input.type (WordOutputV2 | PhraseOutputV2 | SentenceOutputV2). */
  output?: {
    // ── Word-specific (WordOutputV2) ──
    /** Senses ordered by frequency. */
    meanings?: Array<{ pos: string; translation: string }>;
    /** Detailed definitions (source → target bilingual). */
    definitions?: Array<{
      pos: string;
      definition: { source: string; target: string };
    }>;
    /** Usage examples. */
    examples?: Array<{ sentence: string; translation: string }>;
    /** Common collocations. */
    collocations?: Array<{ phrase: string; translation: string }>;
    /** Synonyms (source language only). */
    synonyms?: string[];
    /** CEFR level. */
    cefr?: string;
    // ── Phrase/Sentence (PhraseOutputV2, SentenceOutputV2) ──
    /** Natural translation (phrase & sentence). */
    translation?: string;
  };

  // ── V1 compat — flat explanation (generated by us) ──
  /** Generated from structured data, not stored in DB. */
  explanation?: string;

  [key: string]: unknown;
}

/**
 * Input to buildMarkdownNote — one document with everything needed to render
 * a single Markdown note containing all of its annotation callout cards.
 */
export interface DocumentRenderData {
  doc: DocumentRow;
  /** The annotations to render, in display order. */
  annotations: AnnotationRow[];
  /** Map of annotation ID → parsed AI result (V1 or V2), or undefined. */
  aiResults: Map<string, ParsedAIResult | undefined>;
  /** AI schema version per annotation ID (0 if none). */
  aiVersions: Map<string, number>;
  /** Max AI schema version across the document's annotations (0 if none). */
  aiVersion: number;
  /** Original import date (YYYY-MM-DD). Sticky across re-renders; "" = new. */
  importedAt: string;
  /** Document AI summary, or null. */
  summary: SummaryRow | null;
  /** Vault-relative path of this document's output note. */
  notePath: string;
}

/** The index file tracking all past imports. Document records live in a
 *  separate `documents.jsonl` (see DocumentIndexLine) so the main index stays
 *  tiny regardless of how many documents have been imported. */
export interface ImportIndex {
  /** Schema version — bumped when the index shape changes. */
  formatVersion: number;
  lastImport: string;
  dbPath: string;
}

/** One line of the documents index (`_meta/documents.jsonl`). */
export interface DocumentIndexLine {
  /** The document ID. */
  id: string;
  /** Vault-relative path of this document's note, e.g. "siltflow/<doc>.md". */
  file: string;
  /** Vault-relative path of this document's annotation index (.jsonl),
   *  e.g. "siltflow/_meta/anns/<doc>.jsonl". */
  annsFile: string;
  /** Original import date (YYYY-MM-DD), sticky across re-renders. */
  importedAt: string;
  /** ISO timestamp of the doc summary at last write ("" if none). */
  summaryImportedAt: string;
  lastSync: string;
}

/** One line of a per-document annotation index (.jsonl). */
export interface AnnotationIndexLine {
  /** The annotation ID. */
  id: string;
  /** ISO timestamp of the annotation/ai_result at last write. The annotation
   *  is re-imported when its current `updated_at` is newer. */
  importedAt: string;
  /** ISO timestamp of the ai_result at last write ("" if none at write time).
   *  Lets sync detect when an ai_result was deleted since the last import. */
  aiUpdatedAt?: string;
}
