/**
 * Siltflow SQLite database row types.
 *
 * These match the Drizzle schema in electron/database/schema.ts of the
 * Siltflow desktop app. Only fields needed for import are included.
 */

export interface DocumentRow {
  id: string;
  title: string;
  original_name: string | null;
  total_pages: number | null;
  metadata: string | null; // serialized JSON
  folder_id: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface AnnotationRow {
  id: string;
  document_id: string;
  type: string; // "highlight" | "underline" | "text" | ...
  text: string | null;
  page_number: number | null;
  embed_data: string; // serialized JSON with positional/rect data
  kind: string; // "annotation" | "manual" | ...
  created_at: string;
  updated_at: string;
}

export interface AIResultRow {
  annotation_id: string;
  document_id: string;
  data: string; // serialized JSON — AI translation/explanation/etc.
  version: number; // AI data schema version
  created_at: string;
  updated_at: string;
}

export interface SummaryRow {
  document_id: string;
  text: string;
  is_ai_generated: number; // 0 or 1
  source_lang: string | null;
  created_at: string;
  updated_at: string;
}

export interface FSRSCardRow {
  annotation_id: string;
  document_id: string;
  data: string; // serialized JSON — ts-fsrs Card object
  created_at: string;
  updated_at: string;
}

export interface FolderRow {
  id: string;
  name: string;
  parent_id: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

/**
 * Parsed AI result — union of V1 (AIAnnotationDataV1) and V2 (AIAnnotationDataV2)
 * schemas from the upstream Siltflow desktop app.
 *
 * V1: flat structure with `translation`, `definitions`, `examples`, etc.
 * V2: `input` + `output` where `output` type depends on `input.type`
 *     (word / phrase / sentence).
 */
export interface ParsedAIResult {
  // ── V1 fields ──
  translation?: string;
  source_lang?: string;
  target_lang?: string;
  cleaned_input?: string;
  lemma?: string;
  pos?: string;
  definitions?: Array<{
    pos?: string;
    definition: string;
    gloss?: string;
  }>;
  examples?: Array<{
    sentence: string;
    translation: string;
  }>;
  collocations?: Array<{
    phrase: string;
    translation: string;
  }>;
  alternatives?: Array<{
    expression: string;
    register?: string;
  }>;
  pronunciation?: { ipa?: string };
  metadata?: {
    difficulty?: string;
    register?: string;
    tags?: string[];
  };

  // ── Deprecated V1 fields (legacy compatibility) ──
  /** @deprecated Use translation. */
  translate?: string;
  /** @deprecated Use definitions. */
  words?: Array<{ word: string; pos?: string; meaning: string }>;
  /** @deprecated Use collocations. */
  frequently?: Array<{ phrase: string; translation: string }>;

  // ── V2 fields ──
  input?: {
    text: string;
    normalized: string;
    source_lang: string;
    type: "word" | "phrase" | "sentence";
    lemma?: string | null;
  };
  context?: string | null;
  /** V2 output — shape depends on input.type (WordOutputV2 | PhraseOutputV2 | SentenceOutputV2). */
  output?: {
    // ── Word-specific (WordOutputV2) ──
    /** Senses ordered by frequency. */
    meanings?: Array<{ pos: string; translation: string }>;
    /** Detailed definitions (source → target bilingual). */
    definitions?: Array<{
      pos: string;
      definition: { source: string; target: string };
    }>;
    /** Usage examples. */
    examples?: Array<{ sentence: string; translation: string }>;
    /** Common collocations. */
    collocations?: Array<{ phrase: string; translation: string }>;
    /** Synonyms (source language only). */
    synonyms?: string[];
    /** CEFR level. */
    cefr?: string;
    // ── Phrase/Sentence (PhraseOutputV2, SentenceOutputV2) ──
    /** Natural translation (phrase & sentence). */
    translation?: string;
  };

  // ── V1 compat — flat explanation (generated by us) ──
  /** Generated from structured data, not stored in DB. */
  explanation?: string;

  [key: string]: unknown;
}

/** Grouped data for a single document, ready for Markdown generation. */
export interface DocumentImportData {
  doc: DocumentRow;
  annotations: AnnotationRow[];
  aiResults: Map<string, ParsedAIResult>; // keyed by annotation_id
  aiVersion: number; // max ai_result version across annotations (0 if none)
  summary: SummaryRow | null;
  fsrsCards: FSRSCardRow[];
  /** Resolved folder path in the Obsidian vault (empty string = root of output dir). */
  folderPath: string;
}

/** The index file tracking all past imports. */
export interface ImportIndex {
  lastImport: string;
  dbPath: string;
  documents: Record<
    string,
    {
      file: string;
      annotations: number;
      lastSync: string;
    }
  >;
}
